var topArtists = [
"ABBA",
"AC/DC",
"AeroSmith",
"Aretha Franklin",
"Backstreet Boys",
"Barbra Steisand",
"Beastie Boys",
"Bee Gees",
"Beyonce",
"Billy Joel",
"Black Sabbath",
"Bo Diddley",
"Bob Dylan",
"Bob Marley",
"Bon Jovi",
"Bruce Springsteen",
"Bryan Adams",
"Buddy Holly",
"Carlos Santana",
"Cher",
"Chicago",
"Chuck Berry",
"Celine Dion",
"Creedence Clearwater Revival",
"Curtis Mayfield",
"David Bowie",
"Def Leppard",
"Dianna Ross",
"Donna Summer",
"Dr. Dre",
"Eagles",
"Elton John",
"Elvis Costello",
"Elvis Presley",
"Eminem",
"Eric Clapton",
"Frank Sinatra",
"Garth Brooks",
"George Michael",
"Green-Day",
"Guns N Roses",
"Hank Williams",
"James Brown",
"James Taylor",
"Janet Jackson",
"Jay-Z",
"Jerry Lee Lewis",
"Jimi Hendrix",
"Johnny Cash",
"Joni Mitchell",
"Kiss",
"Led Zeppelin",
"Lionel Richie",
"Littler Richard",
"Lynyrd Skynyrd",
"Madonna",
"Mariah Carey",
"Marvin Gaye",
"Metallica",
"Michael Jackson",
"Motley Crue",
"Muddy Waters",
"Neil Diamond",
"Neil Young",
"Nirvana",
"Olivia Newton-John",
"Ottis Redding",
"Phil Collins",
"Pink Floyd",
"Prince",
"Queen",
"Radiohead",
"Ray Charles",
"REM",
"Richard Marx",
"Rihanna",
"Rod Stewart",
"Roy Orbison",
"Sam Cooke",
"Simon and Garfunkel",
"Smokey Robinson and The Miracles",
"Stevie Wonder",
"Talking Heads",
"The Beach Boys",
"The Beatles",
"The Carpenters",
"The Clash",
"The Doors",
"The Ramones",
"The Rolling Stones",
"The Sex Pistols",
"The Supremes",
"The Temptations",
"The Velvet Underground",
"The Who",
"Tina Turner",
"Tom Petty",
"Tupac Shakur",
"U2",
"Whitney Houston"
];
